# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'sdk-v6-demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'appsflyer-apple-sdk-qa','6.0.0.159'

end

